### ISSUE TITLE
No prebuilt wheels for v1.2.0 on pypi?

### ISSUE THREAD

**Issue by lorengordon** [bebraw/pypandoc#106]
Hello, was it intentional to stop publishing prebuilt wheels to pypi? Just wondering, because the instructions still say the wheel packages include pandoc for Windows and Mac OS X, but the wheels are not listed under the files section on pypi. https://pypi.python.org/pypi/pypandoc/1.2.0

When using the latest version 1.2.0 my builds/checks fail with the pandoc not found error...using download_pandoc() or reverting to v1.1.3 gets them working again.

**Comment by janschulz** [comment]
The problem is simply that I don't have a working package builder right now. 

Apart from that, the new release makes it easier to download the required pandoc binary via an included API method. I tried to keep the language in the README as "neutral" as possible (e.g. if I get my package builder running again, I think it would be nice to build the wheels with pandoc binaries again). If you hve any suggestions how I could make it better, please comment here or file a PR :-)

**Comment by lorengordon** [comment]
Ahh, ok. I do think it is rather convenient to have pandoc in the wheels, especially when testing builds and packaging on Windows using appveyor. What were you using for your builds before? Can you point me towards what was, and now is not working?

**Comment by janschulz** [comment]
https://github.com/janschulz/package-builder/tree/master/recipes/pypandoc

That repo builds conda packages and I hacked in the wheel building in the build scripts for the pypandoc conda package. But now the conda packages are build on conda-forge and not in my private channel). I could probably resurrect the pypandoc recipe and remove the rest...

If you are using conda (with the conda-forge channel) on appveyor, then you can install pandoc from there (conda is installed on appveyor, you just need to add the right path to PATH). The other way is to pip install pypandoc and then just do the oneliner to install pandoc (on windows you don't even need to set path, pypandoc searches the default path).

**Comment by lorengordon** [comment]
Hmm, no, I haven't used conda. Does conda also push packages to pypi? If the pypi upload is already happening separately, perhaps the script building the wheel could be executed by travis ci, using the [`deploy`](https://docs.travis-ci.com/user/deployment/pypi) feature, when a version tag is pushed to the master branch?

**Comment by janschulz** [comment]
no, not by itself. conda is an alternative package manager (nice because it uses precompiled packages, so you can install numpy without setting up a compiler first) and conda-forge has a infrastructure (or better scripts which let you build infrastructure) to build conda packages on CI services (Win, Mac, Linux). I just hacked in the wheel building and upload (via twine).

**Comment by lorengordon** [comment]
Since you support download_pandoc in setup.py, it looks like something as simple as this might work, in .travis.yml?

```
deploy:
  provider: pypi
  user: ...
  password: ...
  distributions: sdist download_pandoc bdist_wheel
  on:
    tags: true
    branch: master
```

**Comment by nueverest** [comment]
@lorengordon Did you try the .travis.yml change that you are suggesting?  I need to ensure support of Win and Mac users.  I too am still using 1.1.3 until a work-around is found.

**Comment by lorengordon** [comment]
I have not yet. I was just figuring out a couple days ago how to incorporate the new `download_pandoc()` function in my projects to workaround it.

I suppose I could mirror this project, update travis.yml there, enable travis in my account, and try deploying to pypi under another name. Doubt I'll get to it for at least a couple weeks, but I'll report back here if it works.

**Comment by bebraw** [comment]
@lorengordon I don't mind adding you as a contributor to the project if you want avoid mirroring. Maybe less hassle.

**Comment by lorengordon** [comment]
Oh, it's no hassle. I just don't want to accidentally deploy a broken package to pypi under this project. I haven't really worked with travis's deploy feature yet, so I'd like to work separately while I figure out how it works. If I get it working, I'll be happy to submit the PR here. :)

**Comment by bebraw** [comment]
Sure, that will work. :+1:

**Comment by ickc** [comment]
I wonder if a service like [pandoc-extras/pandoc-portable](https://github.com/pandoc-extras/pandoc-portable) would help embedding the binaries. Basically it provides a portable version, that upon unzip you can grab the `pandoc` and `pandoc-citeproc` executables.

I didn't finalize the folder structure yet, and [`@jgm` seems to be hesitant](https://github.com/jgm/pandoc/issues/3317#issuecomment-272963420) on a 3rd parties distribution of binaries like this. But if there's a need, there will be a way for this to work out (we can even provide the `.zip` in the official jgm/pandoc).

Alternatively, we can stick to `pandoc_download` only and deprecate this feature.

**Comment by janschulz** [comment]
To get this working, we would need to add macosx tests via travis. I haven't yet looked deeply how to convert the travis setup to run builds on both linux and macosx, but it should be possible. If not, there is always a Circle CI which could take over the linux/source builds.

**Comment by ickc** [comment]
I have a quick skim on the travis setup in pypandoc, it seems that it is doable on Travis' osx build. e.g. see [Testing Your Project on Multiple Operating Systems - Travis CI](https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages%29) on how they splits the tox over different builds.

From my experience, it seems the most tedious part is to get the LaTeX build environment working on it, basically because MacTeX is too large to be build in Travis, BasicTeX is too small to include the packages you need, then you need to install those by `tlmgr`.

**Comment by nueverest** [comment]
On Windows the following works for me. Since 1.1.3 will install pandoc I install that version first.  Then I upgrade pypandoc.  It is a bit of a hack.

```bash
pip install pypandoc==1.1.3
pip install pypandoc --upgrade
```

**Comment by janschulz** [comment]
@nueverest Note that there is now a "API" way to install pandoc after installign pypandoc: `pypandoc.download_pandoc()` will usually do the right thing and make pandoc available to pypandoc...

**Comment by fruch** [comment]
so no wheel support for win/osx anymore ? the README still says there are ?

**Comment by janschulz** [comment]
This might be a way to set up a autobuilder for wheels: https://github.com/joerick/cibuildwheel If someone wants to have a go at that, feel free to send PRs. I'm currently a bit swamped to do the CI dance for that :-/

**Comment by jankatins** [comment]
https://pypi.org/project/py-pandoc/ seems to be a better way to handle this.
