### ISSUE TITLE
latex not properly converted

### ISSUE THREAD

**Issue by nschloe** [bebraw/pypandoc#81]
This
```python
pypandoc.convert('\\"o{A}', 'latex', format='markdown')
```
gives
```python
u'"o\\{A\\}\n'
```
when it should give
```python
u'öA'
```
This is with
```python
>>> pypandoc.__version__
'1.1.2'
```

**Comment by JanSchulz** [comment]
Not sure what's the problem here: if I use pandoc directly, I get this (test.md is `\"o{A}`

```
λ cat c:\data\external\test.md | pandoc -f markdown -t latex
"o\{A\}
```

Just that we are on the same page: the above means that you try to translate from markdown to latex, not from latex to markdown:

```
>>> pypandoc.convert('\\"o{A}', 'markdown', format='latex')
'ö<span>A</span>\r\n'
```

This seems to be more in line with what you expected.

If that's not the problem, I unfortunately don't know latex escaping / umlauts rules (and markdowns) enough to know what's wrong here and what should be the right version here. If you suspect that something is wrong here I would suggest that you bring it up with the pandoc at https://github.com/jgm/pandoc

Sorry that I can't be any more specific :-(

**Comment by nschloe** [comment]
> the above means that you try to translate from markdown to latex, not from latex to markdown:

Got that mixed up. Thanks!
